MODEL:
  META_ARCHITECTURE: "my_Model"
  WEIGHTS: "INPUT THE PATH OF THE PRE-TRAIN WEIGHTS"
  MASK_ON: True
  PIXEL_MEAN: [103.530, 116.280, 123.675]
  PIXEL_STD: [1.0, 1.0, 1.0]
  RESNETS:
    DEPTH: 101
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
    OUT_CHANNELS: 256
  INFERENCE:
    RET_THRES: 0.40
  FEATURE_ENCODER:
    CONVS_DIM: 256
    IN_FEATURES: ['p3','p4','p5']
  SEMANTIC_FPN:
    IN_FEATURES: ['p3', 'p4', 'p5']
    COMMON_STRIDE: 8
DATASETS:
  TRAIN: ("unc_train",)
  TEST: ("unc_testB",)
  ROOT: "INPUT THE ROOT OF THE DATASET"
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 1e-4
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  POLY_LR_POWER: 0.9
  WARMUP_ITERS: 2000
  WARMUP_FACTOR: 0.001
  WARMUP_METHOD: "linear"
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 35.0
  IMS_PER_BATCH: 16
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 30000
INPUT:
  MASK_FORMAT: "bitmask"
  FORMAT: "BGR"
  RANDOM_FLIP: "none"
VERSION: 2
EMB_PATH: "INPUT THE PATH OF THE EMBEDDINGS"
USE_LANG_ATT: True
OUTPUT_DIR: "INPUT THE OUTPUT DIR"
